# RunPod Deployment Configuration for Nala AI DeepSeek R1

[build]
python_version = "3.10"
cuda_version = "11.8"

[build.system_packages]
packages = [
    "git",
    "curl",
    "wget"
]

[build.python_packages]
packages = [
    "torch>=2.0.0",
    "transformers>=4.35.0", 
    "runpod>=1.5.0",
    "accelerate>=0.20.0",
    "bitsandbytes>=0.41.0",
    "sentencepiece>=0.1.99",
    "protobuf>=3.20.0"
]

[runtime]
handler = "runpod/handler.py:handler"
python_path = "/app"

[runtime.environment_variables]
TRANSFORMERS_CACHE = "/runpod-volume/cache"
HF_HOME = "/runpod-volume/cache"
PYTHONPATH = "/app"
MODEL_NAME = "deepseek-ai/DeepSeek-R1"