name: Deploy Progressive Web Terminal

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install --only=dev
      
    - name: Test PWA
      run: |
        echo "Validating PWA configuration..."
        node -e "
          const manifest = require('./manifest.json');
          console.log('✅ Manifest valid:', manifest.name);
          const fs = require('fs');
          if (fs.existsSync('./sw.js')) console.log('✅ Service worker found');
          if (fs.existsSync('./offline.html')) console.log('✅ Offline page found');
        "
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        exclude_assets: '.github,node_modules,.gitignore'